# 01_build_fake_kb_lancedb.py
from __future__ import annotations

from dotenv import load_dotenv
load_dotenv()

import os
import sys
import time
import traceback
from pathlib import Path
from typing import Any, Dict, List

import lancedb
from sentence_transformers import SentenceTransformer


def log(msg: str) -> None:
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)


def build_fake_schema_docs() -> List[Dict[str, Any]]:
    return [
        {
            "doc_type": "schema",
            "doc_id": "dbo.Patient",
            "title": "Table dbo.Patient",
            "text": (
                "CREATE TABLE dbo.Patient ("
                " PatientId INT PRIMARY KEY,"
                " MRN VARCHAR(12) NOT NULL,"
                " DOB DATE NULL,"
                " Sex CHAR(1) NULL,"
                " PostalCode VARCHAR(10) NULL,"
                " CreatedAt DATETIME2 NOT NULL"
                ");"
            ),
        },
        {
            "doc_type": "schema",
            "doc_id": "dbo.Encounter",
            "title": "Table dbo.Encounter",
            "text": (
                "CREATE TABLE dbo.Encounter ("
                " EncounterId BIGINT PRIMARY KEY,"
                " PatientId INT NOT NULL,"
                " EncounterDtm DATETIME2 NOT NULL,"
                " FacilityCode VARCHAR(10) NULL,"
                " ChiefComplaint NVARCHAR(4000) NULL,"
                " TriageAcuity VARCHAR(10) NULL,"
                " Disposition VARCHAR(50) NULL"
                ");"
                " -- FK: dbo.Encounter.PatientId -> dbo.Patient.PatientId"
            ),
        },
        {
            "doc_type": "schema",
            "doc_id": "dbo.Diagnosis",
            "title": "Table dbo.Diagnosis",
            "text": (
                "CREATE TABLE dbo.Diagnosis ("
                " DxId BIGINT PRIMARY KEY,"
                " EncounterId BIGINT NOT NULL,"
                " DxCode VARCHAR(10) NOT NULL,"
                " DxSystem VARCHAR(20) NOT NULL,"
                " DxDescription NVARCHAR(255) NULL,"
                " DxRank INT NULL"
                ");"
                " -- FK: dbo.Diagnosis.EncounterId -> dbo.Encounter.EncounterId"
            ),
        },
    ]


def build_fake_icd_docs() -> List[Dict[str, Any]]:
    icd = [
        # ── SYMPTOMS & SIGNS (R00–R99) ──────────────────────────────────────
        {"code": "R00.0",   "desc": "Tachycardia, unspecified"},
        {"code": "R00.1",   "desc": "Bradycardia, unspecified"},
        {"code": "R00.8",   "desc": "Palpitations"},
        {"code": "R04.0",   "desc": "Epistaxis"},
        {"code": "R04.2",   "desc": "Hemoptysis"},
        {"code": "R05.9",   "desc": "Cough, unspecified"},
        {"code": "R06.00",  "desc": "Dyspnea, unspecified"},
        {"code": "R06.01",  "desc": "Orthopnea"},
        {"code": "R06.09",  "desc": "Other forms of dyspnea"},
        {"code": "R06.1",   "desc": "Stridor"},
        {"code": "R06.2",   "desc": "Wheezing"},
        {"code": "R06.4",   "desc": "Hyperventilation"},
        {"code": "R07.0",   "desc": "Pain in throat"},
        {"code": "R07.1",   "desc": "Chest pain on breathing"},
        {"code": "R07.2",   "desc": "Precordial pain"},
        {"code": "R07.9",   "desc": "Chest pain, unspecified"},
        {"code": "R09.02",  "desc": "Hypoxemia"},
        {"code": "R09.1",   "desc": "Pleurisy"},
        {"code": "R10.0",   "desc": "Acute abdomen"},
        {"code": "R10.10",  "desc": "Upper abdominal pain, unspecified"},
        {"code": "R10.11",  "desc": "Right upper quadrant pain"},
        {"code": "R10.12",  "desc": "Left upper quadrant pain"},
        {"code": "R10.13",  "desc": "Epigastric pain"},
        {"code": "R10.2",   "desc": "Pelvic and perineal pain"},
        {"code": "R10.30",  "desc": "Lower abdominal pain, unspecified"},
        {"code": "R10.31",  "desc": "Right lower quadrant pain"},
        {"code": "R10.32",  "desc": "Left lower quadrant pain"},
        {"code": "R10.33",  "desc": "Periumbilical pain"},
        {"code": "R10.9",   "desc": "Unspecified abdominal pain"},
        {"code": "R11.0",   "desc": "Nausea"},
        {"code": "R11.10",  "desc": "Vomiting, unspecified"},
        {"code": "R11.12",  "desc": "Projectile vomiting"},
        {"code": "R11.2",   "desc": "Nausea with vomiting, unspecified"},
        {"code": "R12",     "desc": "Heartburn"},
        {"code": "R13.10",  "desc": "Dysphagia, unspecified"},
        {"code": "R14.0",   "desc": "Abdominal distension"},
        {"code": "R14.1",   "desc": "Gas pain"},
        {"code": "R17",     "desc": "Unspecified jaundice"},
        {"code": "R18.8",   "desc": "Ascites"},
        {"code": "R19.7",   "desc": "Diarrhea, unspecified"},
        {"code": "R20.2",   "desc": "Paraesthesia of skin"},
        {"code": "R21",     "desc": "Rash and other nonspecific skin eruption"},
        {"code": "R22.0",   "desc": "Localized swelling, mass, lump, head"},
        {"code": "R22.1",   "desc": "Localized swelling, mass, lump, neck"},
        {"code": "R22.2",   "desc": "Localized swelling, mass, lump, trunk"},
        {"code": "R22.31",  "desc": "Localized swelling, mass, lump, right upper limb"},
        {"code": "R22.41",  "desc": "Localized swelling, mass, lump, right lower limb"},
        {"code": "R23.0",   "desc": "Cyanosis"},
        {"code": "R23.1",   "desc": "Pallor"},
        {"code": "R23.2",   "desc": "Flushing"},
        {"code": "R23.3",   "desc": "Spontaneous ecchymoses"},
        {"code": "R25.1",   "desc": "Tremor, unspecified"},
        {"code": "R25.2",   "desc": "Cramp and spasm"},
        {"code": "R26.0",   "desc": "Ataxic gait"},
        {"code": "R26.2",   "desc": "Difficulty in walking, not elsewhere classified"},
        {"code": "R26.81",  "desc": "Unsteadiness on feet"},
        {"code": "R27.0",   "desc": "Ataxia, unspecified"},
        {"code": "R29.1",   "desc": "Meningismus"},
        {"code": "R29.6",   "desc": "Repeated falls"},
        {"code": "R30.0",   "desc": "Dysuria"},
        {"code": "R30.9",   "desc": "Painful micturition, unspecified"},
        {"code": "R31.0",   "desc": "Gross hematuria"},
        {"code": "R31.9",   "desc": "Hematuria, unspecified"},
        {"code": "R32",     "desc": "Unspecified urinary incontinence"},
        {"code": "R33.9",   "desc": "Retention of urine, unspecified"},
        {"code": "R35.0",   "desc": "Frequency of micturition"},
        {"code": "R35.1",   "desc": "Nocturia"},
        {"code": "R39.15",  "desc": "Urgency of urination"},
        {"code": "R40.0",   "desc": "Somnolence"},
        {"code": "R40.1",   "desc": "Stupor"},
        {"code": "R40.20",  "desc": "Unspecified coma"},
        {"code": "R41.0",   "desc": "Disorientation, unspecified"},
        {"code": "R41.3",   "desc": "Other amnesia"},
        {"code": "R41.82",  "desc": "Altered mental status, unspecified"},
        {"code": "R42",     "desc": "Dizziness and giddiness"},
        {"code": "R44.0",   "desc": "Auditory hallucinations"},
        {"code": "R44.1",   "desc": "Visual hallucinations"},
        {"code": "R44.3",   "desc": "Other hallucinations"},
        {"code": "R45.1",   "desc": "Restlessness and agitation"},
        {"code": "R45.5",   "desc": "Hostility"},
        {"code": "R45.851", "desc": "Suicidal ideations"},
        {"code": "R45.850", "desc": "Homicidal ideations"},
        {"code": "R47.01",  "desc": "Aphasia"},
        {"code": "R47.1",   "desc": "Dysarthria"},
        {"code": "R49.0",   "desc": "Dysphonia"},
        {"code": "R50.9",   "desc": "Fever, unspecified"},
        {"code": "R50.81",  "desc": "Fever presenting with conditions classified elsewhere"},
        {"code": "R51.9",   "desc": "Headache, unspecified"},
        {"code": "R52",     "desc": "Pain, unspecified"},
        {"code": "R53.1",   "desc": "Weakness"},
        {"code": "R53.83",  "desc": "Other fatigue"},
        {"code": "R55",     "desc": "Syncope and collapse"},
        {"code": "R56.00",  "desc": "Simple febrile convulsions"},
        {"code": "R56.9",   "desc": "Unspecified convulsions"},
        {"code": "R57.0",   "desc": "Cardiogenic shock"},
        {"code": "R57.1",   "desc": "Hypovolemic shock"},
        {"code": "R57.9",   "desc": "Shock, unspecified"},
        {"code": "R58",     "desc": "Hemorrhage, not elsewhere classified"},
        {"code": "R59.0",   "desc": "Localized enlarged lymph nodes"},
        {"code": "R60.0",   "desc": "Localized edema"},
        {"code": "R60.1",   "desc": "Generalized edema"},
        {"code": "R60.9",   "desc": "Edema, unspecified"},
        {"code": "R63.0",   "desc": "Anorexia"},
        {"code": "R63.4",   "desc": "Abnormal weight loss"},
        {"code": "R63.5",   "desc": "Abnormal weight gain"},
        {"code": "R65.10",  "desc": "Systemic inflammatory response syndrome without organ dysfunction"},
        {"code": "R65.20",  "desc": "Severe sepsis without septic shock"},
        {"code": "R65.21",  "desc": "Severe sepsis with septic shock"},
        {"code": "R68.83",  "desc": "Chills without fever"},
        {"code": "R73.09",  "desc": "Other abnormal glucose"},
        {"code": "R79.1",   "desc": "Abnormal coagulation profile"},
        # ── CARDIOVASCULAR (I00–I99) ─────────────────────────────────────────
        {"code": "I10",     "desc": "Essential (primary) hypertension"},
        {"code": "I11.0",   "desc": "Hypertensive heart disease with heart failure"},
        {"code": "I11.9",   "desc": "Hypertensive heart disease without heart failure"},
        {"code": "I20.0",   "desc": "Unstable angina"},
        {"code": "I20.1",   "desc": "Angina pectoris with documented spasm"},
        {"code": "I20.9",   "desc": "Angina pectoris, unspecified"},
        {"code": "I21.4",   "desc": "Non-ST elevation myocardial infarction"},
        {"code": "I21.9",   "desc": "Acute myocardial infarction, unspecified"},
        {"code": "I21.01",  "desc": "ST elevation MI of left main coronary artery"},
        {"code": "I21.11",  "desc": "ST elevation MI of right coronary artery"},
        {"code": "I26.09",  "desc": "Pulmonary embolism without acute cor pulmonale"},
        {"code": "I26.99",  "desc": "Other pulmonary embolism without acute cor pulmonale"},
        {"code": "I30.9",   "desc": "Acute pericarditis, unspecified"},
        {"code": "I31.3",   "desc": "Pericardial effusion (noninflammatory)"},
        {"code": "I33.0",   "desc": "Acute and subacute infective endocarditis"},
        {"code": "I40.9",   "desc": "Acute myocarditis, unspecified"},
        {"code": "I42.0",   "desc": "Dilated cardiomyopathy"},
        {"code": "I44.2",   "desc": "Atrioventricular block, complete"},
        {"code": "I46.0",   "desc": "Cardiac arrest with successful resuscitation"},
        {"code": "I46.9",   "desc": "Cardiac arrest, cause unspecified"},
        {"code": "I47.1",   "desc": "Supraventricular tachycardia"},
        {"code": "I47.2",   "desc": "Ventricular tachycardia"},
        {"code": "I48.0",   "desc": "Paroxysmal atrial fibrillation"},
        {"code": "I48.19",  "desc": "Other persistent atrial fibrillation"},
        {"code": "I48.20",  "desc": "Chronic atrial fibrillation, unspecified"},
        {"code": "I48.91",  "desc": "Unspecified atrial fibrillation"},
        {"code": "I49.01",  "desc": "Ventricular fibrillation"},
        {"code": "I50.21",  "desc": "Acute systolic heart failure"},
        {"code": "I50.22",  "desc": "Chronic systolic heart failure"},
        {"code": "I50.23",  "desc": "Acute on chronic systolic heart failure"},
        {"code": "I50.31",  "desc": "Acute diastolic heart failure"},
        {"code": "I50.33",  "desc": "Acute on chronic diastolic heart failure"},
        {"code": "I50.9",   "desc": "Heart failure, unspecified"},
        {"code": "I63.9",   "desc": "Cerebral infarction, unspecified"},
        {"code": "I64",     "desc": "Stroke, not specified as haemorrhage or infarction"},
        {"code": "I67.0",   "desc": "Dissection of cerebral arteries, nonruptured"},
        {"code": "I71.00",  "desc": "Dissection of unspecified site of aorta"},
        {"code": "I71.01",  "desc": "Dissection of thoracic aorta"},
        {"code": "I71.02",  "desc": "Dissection of abdominal aorta"},
        {"code": "I71.4",   "desc": "Abdominal aortic aneurysm without rupture"},
        {"code": "I74.3",   "desc": "Embolism and thrombosis of arteries of lower extremities"},
        {"code": "I80.10",  "desc": "Phlebitis and thrombophlebitis of unspecified femoral vein"},
        {"code": "I82.401", "desc": "Acute deep vein thrombosis, right lower extremity"},
        {"code": "I82.402", "desc": "Acute deep vein thrombosis, left lower extremity"},
        {"code": "I95.1",   "desc": "Orthostatic hypotension"},
        {"code": "I95.9",   "desc": "Hypotension, unspecified"},
        {"code": "I45.10",  "desc": "Unspecified right bundle-branch block"},
        {"code": "I25.10",  "desc": "Atherosclerotic heart disease without angina"},
        {"code": "I25.110", "desc": "Atherosclerotic heart disease with unstable angina"},
        # ── RESPIRATORY (J00–J99) ────────────────────────────────────────────
        {"code": "J00",     "desc": "Acute nasopharyngitis (common cold)"},
        {"code": "J01.00",  "desc": "Acute maxillary sinusitis, unspecified"},
        {"code": "J01.10",  "desc": "Acute frontal sinusitis, unspecified"},
        {"code": "J01.90",  "desc": "Acute sinusitis, unspecified"},
        {"code": "J02.0",   "desc": "Streptococcal pharyngitis"},
        {"code": "J02.9",   "desc": "Acute pharyngitis, unspecified"},
        {"code": "J03.00",  "desc": "Acute streptococcal tonsillitis, unspecified"},
        {"code": "J03.90",  "desc": "Acute tonsillitis, unspecified"},
        {"code": "J04.0",   "desc": "Acute laryngitis"},
        {"code": "J04.1",   "desc": "Acute tracheitis without obstruction"},
        {"code": "J05.0",   "desc": "Acute obstructive laryngitis (croup)"},
        {"code": "J06.0",   "desc": "Acute laryngopharyngitis"},
        {"code": "J06.9",   "desc": "Acute upper respiratory infection, unspecified"},
        {"code": "J10.1",   "desc": "Influenza with other respiratory manifestations"},
        {"code": "J11.1",   "desc": "Influenza with other respiratory manifestations, virus not identified"},
        {"code": "J12.9",   "desc": "Viral pneumonia, unspecified"},
        {"code": "J13",     "desc": "Pneumonia due to Streptococcus pneumoniae"},
        {"code": "J14",     "desc": "Pneumonia due to Haemophilus influenzae"},
        {"code": "J15.0",   "desc": "Pneumonia due to Klebsiella pneumoniae"},
        {"code": "J15.212", "desc": "Pneumonia due to Methicillin resistant Staphylococcus aureus"},
        {"code": "J18.0",   "desc": "Bronchopneumonia, unspecified organism"},
        {"code": "J18.1",   "desc": "Lobar pneumonia, unspecified organism"},
        {"code": "J18.9",   "desc": "Pneumonia, unspecified organism"},
        {"code": "J20.9",   "desc": "Acute bronchitis, unspecified"},
        {"code": "J21.0",   "desc": "Acute bronchiolitis due to respiratory syncytial virus"},
        {"code": "J21.9",   "desc": "Acute bronchiolitis, unspecified"},
        {"code": "J22",     "desc": "Unspecified acute lower respiratory infection"},
        {"code": "J30.1",   "desc": "Allergic rhinitis due to pollen"},
        {"code": "J30.9",   "desc": "Allergic rhinitis, unspecified"},
        {"code": "J36",     "desc": "Peritonsillar abscess"},
        {"code": "J40",     "desc": "Bronchitis, not specified as acute or chronic"},
        {"code": "J44.0",   "desc": "COPD with acute lower respiratory infection"},
        {"code": "J44.1",   "desc": "COPD with acute exacerbation"},
        {"code": "J44.9",   "desc": "COPD, unspecified"},
        {"code": "J45.21",  "desc": "Mild intermittent asthma with acute exacerbation"},
        {"code": "J45.31",  "desc": "Mild persistent asthma with acute exacerbation"},
        {"code": "J45.41",  "desc": "Moderate persistent asthma with acute exacerbation"},
        {"code": "J45.51",  "desc": "Severe persistent asthma with acute exacerbation"},
        {"code": "J45.901", "desc": "Unspecified asthma with acute exacerbation"},
        {"code": "J45.90",  "desc": "Unspecified asthma, uncomplicated"},
        {"code": "J80",     "desc": "Acute respiratory distress syndrome"},
        {"code": "J81.0",   "desc": "Acute pulmonary edema"},
        {"code": "J93.0",   "desc": "Spontaneous tension pneumothorax"},
        {"code": "J93.11",  "desc": "Primary spontaneous pneumothorax"},
        {"code": "J93.12",  "desc": "Secondary spontaneous pneumothorax"},
        {"code": "J96.00",  "desc": "Acute respiratory failure, unspecified"},
        {"code": "J96.01",  "desc": "Acute respiratory failure with hypoxia"},
        {"code": "J96.02",  "desc": "Acute respiratory failure with hypercapnia"},
        {"code": "J90",     "desc": "Pleural effusion, not elsewhere classified"},
        {"code": "J84.10",  "desc": "Pulmonary fibrosis, unspecified"},
        # ── GASTROINTESTINAL (K00–K95) ───────────────────────────────────────
        {"code": "K08.81",  "desc": "Dental pain"},
        {"code": "K21.0",   "desc": "Gastro-oesophageal reflux disease with oesophagitis"},
        {"code": "K21.9",   "desc": "Gastro-oesophageal reflux disease without oesophagitis"},
        {"code": "K25.0",   "desc": "Acute gastric ulcer with haemorrhage"},
        {"code": "K25.9",   "desc": "Gastric ulcer, unspecified"},
        {"code": "K26.0",   "desc": "Acute duodenal ulcer with haemorrhage"},
        {"code": "K29.00",  "desc": "Acute gastritis without bleeding"},
        {"code": "K29.01",  "desc": "Acute gastritis with bleeding"},
        {"code": "K29.70",  "desc": "Gastritis, unspecified, without bleeding"},
        {"code": "K30",     "desc": "Functional dyspepsia"},
        {"code": "K35.20",  "desc": "Acute appendicitis with generalized peritonitis"},
        {"code": "K35.80",  "desc": "Acute appendicitis without peritonitis or abscess"},
        {"code": "K37",     "desc": "Unspecified appendicitis"},
        {"code": "K40.90",  "desc": "Unilateral inguinal hernia, without obstruction or gangrene"},
        {"code": "K40.30",  "desc": "Unilateral inguinal hernia with obstruction, without gangrene"},
        {"code": "K42.0",   "desc": "Umbilical hernia with obstruction"},
        {"code": "K42.9",   "desc": "Umbilical hernia without obstruction or gangrene"},
        {"code": "K50.90",  "desc": "Crohn's disease, unspecified, without complications"},
        {"code": "K51.90",  "desc": "Ulcerative colitis, unspecified, without complications"},
        {"code": "K52.9",   "desc": "Noninfective gastroenteritis and colitis, unspecified"},
        {"code": "K56.0",   "desc": "Paralytic ileus"},
        {"code": "K56.50",  "desc": "Intestinal adhesions with partial obstruction"},
        {"code": "K56.609", "desc": "Unspecified intestinal obstruction"},
        {"code": "K57.20",  "desc": "Diverticulitis of large intestine without perforation"},
        {"code": "K57.30",  "desc": "Diverticulosis of large intestine without perforation"},
        {"code": "K60.0",   "desc": "Acute anal fissure"},
        {"code": "K61.0",   "desc": "Anal abscess"},
        {"code": "K64.0",   "desc": "First degree haemorrhoids"},
        {"code": "K64.9",   "desc": "Unspecified haemorrhoids"},
        {"code": "K70.30",  "desc": "Alcoholic cirrhosis of liver without ascites"},
        {"code": "K72.90",  "desc": "Hepatic failure, unspecified without coma"},
        {"code": "K74.60",  "desc": "Unspecified cirrhosis of liver"},
        {"code": "K75.0",   "desc": "Abscess of liver"},
        {"code": "K76.0",   "desc": "Fatty (change of) liver"},
        {"code": "K80.00",  "desc": "Calculus of gallbladder with acute cholecystitis without obstruction"},
        {"code": "K80.20",  "desc": "Calculus of gallbladder without cholecystitis, without obstruction"},
        {"code": "K81.0",   "desc": "Acute cholecystitis"},
        {"code": "K81.9",   "desc": "Cholecystitis, unspecified"},
        {"code": "K83.0",   "desc": "Cholangitis"},
        {"code": "K85.90",  "desc": "Acute pancreatitis without necrosis or infection, unspecified"},
        {"code": "K86.1",   "desc": "Other chronic pancreatitis"},
        {"code": "K92.0",   "desc": "Haematemesis"},
        {"code": "K92.1",   "desc": "Melaena"},
        {"code": "K92.2",   "desc": "Gastrointestinal haemorrhage, unspecified"},
        # ── GENITOURINARY (N00–N99) ──────────────────────────────────────────
        {"code": "N10",     "desc": "Acute pyelonephritis"},
        {"code": "N11.9",   "desc": "Chronic tubulo-interstitial nephritis, unspecified"},
        {"code": "N13.30",  "desc": "Unspecified hydronephrosis"},
        {"code": "N17.0",   "desc": "Acute kidney failure with tubular necrosis"},
        {"code": "N17.9",   "desc": "Acute kidney failure, unspecified"},
        {"code": "N18.3",   "desc": "Chronic kidney disease, stage 3 (moderate)"},
        {"code": "N18.4",   "desc": "Chronic kidney disease, stage 4 (severe)"},
        {"code": "N18.5",   "desc": "Chronic kidney disease, stage 5"},
        {"code": "N18.6",   "desc": "End stage renal disease"},
        {"code": "N20.0",   "desc": "Calculus of kidney"},
        {"code": "N20.1",   "desc": "Calculus of ureter"},
        {"code": "N20.9",   "desc": "Urinary calculus, unspecified"},
        {"code": "N23",     "desc": "Unspecified renal colic"},
        {"code": "N30.00",  "desc": "Acute cystitis without haematuria"},
        {"code": "N30.01",  "desc": "Acute cystitis with haematuria"},
        {"code": "N39.0",   "desc": "Urinary tract infection, site not specified"},
        {"code": "N39.3",   "desc": "Stress incontinence (female)"},
        {"code": "N39.41",  "desc": "Urge incontinence"},
        {"code": "N40.0",   "desc": "Benign prostatic hyperplasia without lower urinary tract symptoms"},
        {"code": "N40.1",   "desc": "Benign prostatic hyperplasia with lower urinary tract symptoms"},
        {"code": "N41.0",   "desc": "Acute prostatitis"},
        {"code": "N41.1",   "desc": "Chronic prostatitis"},
        {"code": "N44.01",  "desc": "Extravaginal torsion of spermatic cord"},
        {"code": "N44.02",  "desc": "Intravaginal torsion of spermatic cord"},
        {"code": "N45.1",   "desc": "Epididymitis"},
        {"code": "N45.3",   "desc": "Epididymo-orchitis"},
        {"code": "N70.01",  "desc": "Acute salpingitis"},
        {"code": "N70.91",  "desc": "Salpingitis, unspecified"},
        {"code": "N73.0",   "desc": "Acute parametritis and pelvic cellulitis"},
        {"code": "N73.9",   "desc": "Female pelvic inflammatory disease, unspecified"},
        {"code": "N76.0",   "desc": "Acute vaginitis"},
        {"code": "N80.0",   "desc": "Endometriosis of uterus"},
        {"code": "N83.20",  "desc": "Unspecified ovarian cyst"},
        {"code": "N94.6",   "desc": "Dysmenorrhoea, unspecified"},
        {"code": "N95.0",   "desc": "Postmenopausal bleeding"},
        # ── NEUROLOGY (G00–G99) ──────────────────────────────────────────────
        {"code": "G00.9",   "desc": "Bacterial meningitis, unspecified"},
        {"code": "G03.9",   "desc": "Meningitis, unspecified"},
        {"code": "G04.90",  "desc": "Encephalitis and encephalomyelitis, unspecified"},
        {"code": "G20",     "desc": "Parkinson's disease"},
        {"code": "G25.0",   "desc": "Essential tremor"},
        {"code": "G25.81",  "desc": "Restless legs syndrome"},
        {"code": "G35",     "desc": "Multiple sclerosis"},
        {"code": "G40.009", "desc": "Localization-related epilepsy without status epilepticus, unspecified"},
        {"code": "G40.909", "desc": "Epilepsy, unspecified, not intractable, without status epilepticus"},
        {"code": "G41.0",   "desc": "Grand mal status epilepticus"},
        {"code": "G43.009", "desc": "Migraine without aura, not intractable"},
        {"code": "G43.109", "desc": "Migraine with aura, not intractable"},
        {"code": "G43.909", "desc": "Migraine, unspecified, not intractable"},
        {"code": "G44.009", "desc": "Cluster headache syndrome, unspecified, not intractable"},
        {"code": "G44.309", "desc": "Post-traumatic headache, unspecified, not intractable"},
        {"code": "G45.0",   "desc": "Vertebro-basilar artery syndrome"},
        {"code": "G45.9",   "desc": "Transient cerebral ischaemic attack, unspecified"},
        {"code": "G47.00",  "desc": "Insomnia, unspecified"},
        {"code": "G47.30",  "desc": "Sleep apnoea, unspecified"},
        {"code": "G47.33",  "desc": "Obstructive sleep apnoea"},
        {"code": "G50.0",   "desc": "Trigeminal neuralgia"},
        {"code": "G51.0",   "desc": "Bell palsy"},
        {"code": "G54.2",   "desc": "Cervical root disorders, not elsewhere classified"},
        {"code": "G54.4",   "desc": "Lumbosacral root disorders"},
        {"code": "G56.00",  "desc": "Carpal tunnel syndrome, unspecified upper limb"},
        {"code": "G57.00",  "desc": "Lesion of sciatic nerve, unspecified lower limb"},
        {"code": "G61.0",   "desc": "Guillain-Barré syndrome"},
        {"code": "G62.9",   "desc": "Polyneuropathy, unspecified"},
        {"code": "G70.01",  "desc": "Myasthenia gravis with acute exacerbation"},
        {"code": "G89.11",  "desc": "Acute pain due to trauma"},
        {"code": "G89.21",  "desc": "Chronic pain due to trauma"},
        {"code": "G89.29",  "desc": "Other chronic pain"},
        {"code": "G89.4",   "desc": "Chronic pain syndrome"},
        {"code": "G93.1",   "desc": "Anoxic brain damage, not elsewhere classified"},
        {"code": "G93.40",  "desc": "Encephalopathy, unspecified"},
        {"code": "G93.41",  "desc": "Metabolic encephalopathy"},
        {"code": "G93.6",   "desc": "Cerebral oedema"},
        {"code": "G96.0",   "desc": "Cerebrospinal fluid leak"},
        # ── MENTAL HEALTH (F00–F99) ──────────────────────────────────────────
        {"code": "F05",     "desc": "Delirium due to known physiological condition"},
        {"code": "F10.10",  "desc": "Alcohol abuse, uncomplicated"},
        {"code": "F10.120", "desc": "Alcohol abuse with intoxication, uncomplicated"},
        {"code": "F10.20",  "desc": "Alcohol dependence, uncomplicated"},
        {"code": "F10.230", "desc": "Alcohol dependence with withdrawal, uncomplicated"},
        {"code": "F10.231", "desc": "Alcohol dependence with withdrawal delirium"},
        {"code": "F11.10",  "desc": "Opioid abuse, uncomplicated"},
        {"code": "F11.120", "desc": "Opioid abuse with intoxication, uncomplicated"},
        {"code": "F11.20",  "desc": "Opioid dependence, uncomplicated"},
        {"code": "F12.120", "desc": "Cannabis abuse with intoxication, uncomplicated"},
        {"code": "F13.230", "desc": "Sedative dependence with withdrawal, uncomplicated"},
        {"code": "F14.120", "desc": "Cocaine abuse with intoxication, uncomplicated"},
        {"code": "F15.120", "desc": "Other stimulant abuse with intoxication, uncomplicated"},
        {"code": "F19.120", "desc": "Other psychoactive substance abuse with intoxication, uncomplicated"},
        {"code": "F20.0",   "desc": "Paranoid schizophrenia"},
        {"code": "F20.9",   "desc": "Schizophrenia, unspecified"},
        {"code": "F23",     "desc": "Brief psychotic disorder"},
        {"code": "F25.0",   "desc": "Schizoaffective disorder, bipolar type"},
        {"code": "F25.9",   "desc": "Schizoaffective disorder, unspecified"},
        {"code": "F31.10",  "desc": "Bipolar disorder, current episode manic without psychotic features, unspecified"},
        {"code": "F31.9",   "desc": "Bipolar disorder, unspecified"},
        {"code": "F32.0",   "desc": "Major depressive disorder, single episode, mild"},
        {"code": "F32.1",   "desc": "Major depressive disorder, single episode, moderate"},
        {"code": "F32.2",   "desc": "Major depressive disorder, single episode, severe without psychotic features"},
        {"code": "F32.3",   "desc": "Major depressive disorder, single episode, severe with psychotic features"},
        {"code": "F32.9",   "desc": "Major depressive disorder, single episode, unspecified"},
        {"code": "F33.1",   "desc": "Major depressive disorder, recurrent, moderate"},
        {"code": "F33.9",   "desc": "Major depressive disorder, recurrent, unspecified"},
        {"code": "F40.00",  "desc": "Agoraphobia without panic disorder"},
        {"code": "F41.0",   "desc": "Panic disorder without agoraphobia"},
        {"code": "F41.1",   "desc": "Generalised anxiety disorder"},
        {"code": "F41.9",   "desc": "Anxiety disorder, unspecified"},
        {"code": "F42.9",   "desc": "Obsessive-compulsive disorder, unspecified"},
        {"code": "F43.0",   "desc": "Acute stress reaction"},
        {"code": "F43.10",  "desc": "Post-traumatic stress disorder, unspecified"},
        {"code": "F43.12",  "desc": "Post-traumatic stress disorder, chronic"},
        {"code": "F43.21",  "desc": "Adjustment disorder with depressed mood"},
        {"code": "F43.22",  "desc": "Adjustment disorder with anxiety"},
        {"code": "F43.23",  "desc": "Adjustment disorder with mixed anxiety and depressed mood"},
        {"code": "F50.00",  "desc": "Anorexia nervosa, unspecified"},
        {"code": "F50.2",   "desc": "Bulimia nervosa"},
        {"code": "F60.3",   "desc": "Borderline personality disorder"},
        {"code": "F60.9",   "desc": "Personality disorder, unspecified"},
        {"code": "F90.9",   "desc": "Attention-deficit hyperactivity disorder, unspecified type"},
        {"code": "F99",     "desc": "Mental disorder, not otherwise specified"},
        # ── MUSCULOSKELETAL (M00–M99) ────────────────────────────────────────
        {"code": "M00.9",   "desc": "Pyogenic arthritis, unspecified"},
        {"code": "M06.9",   "desc": "Rheumatoid arthritis, unspecified"},
        {"code": "M10.00",  "desc": "Idiopathic gout, unspecified site"},
        {"code": "M10.07",  "desc": "Idiopathic gout, ankle and foot"},
        {"code": "M10.9",   "desc": "Gout, unspecified"},
        {"code": "M13.0",   "desc": "Polyarthritis, unspecified"},
        {"code": "M16.9",   "desc": "Osteoarthritis of hip, unspecified"},
        {"code": "M17.11",  "desc": "Primary osteoarthritis, right knee"},
        {"code": "M17.12",  "desc": "Primary osteoarthritis, left knee"},
        {"code": "M17.9",   "desc": "Osteoarthritis of knee, unspecified"},
        {"code": "M25.311", "desc": "Pain in right shoulder"},
        {"code": "M25.312", "desc": "Pain in left shoulder"},
        {"code": "M25.321", "desc": "Pain in right elbow"},
        {"code": "M25.361", "desc": "Pain in right knee"},
        {"code": "M25.362", "desc": "Pain in left knee"},
        {"code": "M25.371", "desc": "Pain in right ankle"},
        {"code": "M35.0",   "desc": "Sjögren syndrome"},
        {"code": "M45.0",   "desc": "Ankylosing spondylitis of multiple sites in spine"},
        {"code": "M47.816", "desc": "Spondylosis without myelopathy or radiculopathy, lumbar region"},
        {"code": "M48.06",  "desc": "Spinal stenosis, lumbar region"},
        {"code": "M50.20",  "desc": "Other cervical disc displacement, unspecified cervical region"},
        {"code": "M51.16",  "desc": "Intervertebral disc degeneration, lumbar region"},
        {"code": "M54.2",   "desc": "Cervicalgia"},
        {"code": "M54.30",  "desc": "Sciatica, unspecified side"},
        {"code": "M54.31",  "desc": "Sciatica, right side"},
        {"code": "M54.32",  "desc": "Sciatica, left side"},
        {"code": "M54.40",  "desc": "Lumbago with sciatica, unspecified side"},
        {"code": "M54.41",  "desc": "Lumbago with sciatica, right side"},
        {"code": "M54.50",  "desc": "Low back pain, unspecified"},
        {"code": "M54.51",  "desc": "Vertebrogenic low back pain"},
        {"code": "M54.9",   "desc": "Dorsalgia, unspecified"},
        {"code": "M62.830", "desc": "Muscle spasm"},
        {"code": "M65.30",  "desc": "Trigger finger, unspecified finger"},
        {"code": "M70.50",  "desc": "Bursitis of hip, unspecified hip"},
        {"code": "M75.0",   "desc": "Adhesive capsulitis of shoulder"},
        {"code": "M75.1",   "desc": "Rotator cuff syndrome"},
        {"code": "M76.60",  "desc": "Achilles tendinitis, unspecified leg"},
        {"code": "M77.11",  "desc": "Lateral epicondylitis, right elbow"},
        {"code": "M79.1",   "desc": "Myalgia"},
        {"code": "M79.2",   "desc": "Neuralgia and neuritis, unspecified"},
        {"code": "M79.3",   "desc": "Panniculitis, unspecified"},
        {"code": "M79.7",   "desc": "Fibromyalgia"},
        {"code": "M81.0",   "desc": "Age-related osteoporosis without current pathological fracture"},
        {"code": "M86.9",   "desc": "Osteomyelitis, unspecified"},
        # ── INFECTIOUS & PARASITIC (A00–B99) ────────────────────────────────
        {"code": "A04.5",   "desc": "Campylobacter enteritis"},
        {"code": "A04.7",   "desc": "Enterocolitis due to Clostridium difficile"},
        {"code": "A08.0",   "desc": "Rotaviral enteritis"},
        {"code": "A09",     "desc": "Infectious gastroenteritis and colitis, unspecified"},
        {"code": "A40.0",   "desc": "Sepsis due to streptococcus, group A"},
        {"code": "A40.9",   "desc": "Streptococcal sepsis, unspecified"},
        {"code": "A41.01",  "desc": "Sepsis due to Methicillin susceptible Staphylococcus aureus"},
        {"code": "A41.02",  "desc": "Sepsis due to Methicillin resistant Staphylococcus aureus"},
        {"code": "A41.50",  "desc": "Gram-negative sepsis, unspecified"},
        {"code": "A41.51",  "desc": "Sepsis due to Escherichia coli"},
        {"code": "A41.9",   "desc": "Sepsis, unspecified organism"},
        {"code": "A49.0",   "desc": "Staphylococcal infection, unspecified site"},
        {"code": "A49.1",   "desc": "Streptococcal infection, unspecified site"},
        {"code": "A49.9",   "desc": "Bacterial infection, unspecified"},
        {"code": "A54.00",  "desc": "Gonorrhoea, unspecified"},
        {"code": "A56.00",  "desc": "Chlamydial infection of lower genitourinary tract, unspecified"},
        {"code": "A60.00",  "desc": "Herpesviral infection of urogenital system, unspecified"},
        {"code": "A69.20",  "desc": "Lyme disease, unspecified"},
        {"code": "B00.1",   "desc": "Herpesviral vesicular dermatitis"},
        {"code": "B00.9",   "desc": "Herpesviral infection, unspecified"},
        {"code": "B01.9",   "desc": "Varicella without complication"},
        {"code": "B02.20",  "desc": "Postherpetic neuralgia, unspecified"},
        {"code": "B02.29",  "desc": "Other postherpetic nervous system involvement"},
        {"code": "B02.9",   "desc": "Zoster without complications"},
        {"code": "B15.9",   "desc": "Acute hepatitis A without hepatic coma"},
        {"code": "B16.9",   "desc": "Acute hepatitis B without delta-agent and without hepatic coma"},
        {"code": "B17.10",  "desc": "Acute hepatitis C without hepatic coma"},
        {"code": "B18.2",   "desc": "Chronic viral hepatitis C"},
        {"code": "B20",     "desc": "Human immunodeficiency virus (HIV) disease"},
        {"code": "B34.9",   "desc": "Viral infection, unspecified"},
        {"code": "B37.0",   "desc": "Candidal stomatitis"},
        {"code": "B37.3",   "desc": "Candidiasis of vulva and vagina"},
        {"code": "B37.9",   "desc": "Candidiasis, unspecified"},
        # ── ENDOCRINE & METABOLIC (E00–E90) ─────────────────────────────────
        {"code": "E03.9",   "desc": "Hypothyroidism, unspecified"},
        {"code": "E05.00",  "desc": "Thyrotoxicosis with diffuse goitre without thyrotoxic crisis"},
        {"code": "E05.90",  "desc": "Thyrotoxicosis, unspecified without thyrotoxic crisis"},
        {"code": "E06.3",   "desc": "Autoimmune thyroiditis"},
        {"code": "E10.10",  "desc": "Type 1 diabetes mellitus with ketoacidosis without coma"},
        {"code": "E10.11",  "desc": "Type 1 diabetes mellitus with ketoacidosis with coma"},
        {"code": "E10.649", "desc": "Type 1 diabetes mellitus with hypoglycaemia without coma"},
        {"code": "E10.65",  "desc": "Type 1 diabetes mellitus with hyperglycaemia"},
        {"code": "E10.9",   "desc": "Type 1 diabetes mellitus without complications"},
        {"code": "E11.10",  "desc": "Type 2 diabetes mellitus with ketoacidosis without coma"},
        {"code": "E11.649", "desc": "Type 2 diabetes mellitus with hypoglycaemia without coma"},
        {"code": "E11.65",  "desc": "Type 2 diabetes mellitus with hyperglycaemia"},
        {"code": "E11.9",   "desc": "Type 2 diabetes mellitus without complications"},
        {"code": "E16.0",   "desc": "Drug-induced hypoglycaemia without coma"},
        {"code": "E16.2",   "desc": "Hypoglycaemia, unspecified"},
        {"code": "E21.0",   "desc": "Primary hyperparathyroidism"},
        {"code": "E27.40",  "desc": "Adrenocortical insufficiency, unspecified"},
        {"code": "E43",     "desc": "Unspecified severe protein-calorie malnutrition"},
        {"code": "E55.9",   "desc": "Vitamin D deficiency, unspecified"},
        {"code": "E61.1",   "desc": "Iron deficiency"},
        {"code": "E66.01",  "desc": "Morbid (severe) obesity due to excess calories"},
        {"code": "E66.9",   "desc": "Obesity, unspecified"},
        {"code": "E78.00",  "desc": "Pure hypercholesterolaemia, unspecified"},
        {"code": "E78.5",   "desc": "Hyperlipidaemia, unspecified"},
        {"code": "E83.52",  "desc": "Hypercalcaemia"},
        {"code": "E87.0",   "desc": "Hyperosmolality and hypernatraemia"},
        {"code": "E87.1",   "desc": "Hypo-osmolality and hyponatraemia"},
        {"code": "E87.5",   "desc": "Hyperkalaemia"},
        {"code": "E87.6",   "desc": "Hypokalaemia"},
        {"code": "E87.8",   "desc": "Other disorders of electrolyte and fluid balance"},
        # ── SKIN & SUBCUTANEOUS (L00–L99) ────────────────────────────────────
        {"code": "L01.00",  "desc": "Impetigo, unspecified"},
        {"code": "L02.91",  "desc": "Cutaneous abscess, unspecified"},
        {"code": "L03.90",  "desc": "Cellulitis, unspecified"},
        {"code": "L03.211", "desc": "Cellulitis of face"},
        {"code": "L04.9",   "desc": "Acute lymphadenitis, unspecified"},
        {"code": "L05.01",  "desc": "Pilonidal cyst with abscess"},
        {"code": "L20.9",   "desc": "Atopic dermatitis, unspecified"},
        {"code": "L23.9",   "desc": "Allergic contact dermatitis, unspecified cause"},
        {"code": "L27.0",   "desc": "Generalised skin eruption due to drugs taken internally"},
        {"code": "L30.9",   "desc": "Dermatitis, unspecified"},
        {"code": "L40.0",   "desc": "Psoriasis vulgaris"},
        {"code": "L50.0",   "desc": "Allergic urticaria"},
        {"code": "L50.9",   "desc": "Urticaria, unspecified"},
        {"code": "L51.1",   "desc": "Stevens-Johnson syndrome"},
        {"code": "L51.2",   "desc": "Toxic epidermal necrolysis"},
        {"code": "L52",     "desc": "Erythema nodosum"},
        {"code": "L55.0",   "desc": "Sunburn of first degree"},
        {"code": "L70.0",   "desc": "Acne vulgaris"},
        {"code": "L72.0",   "desc": "Epidermal cyst"},
        {"code": "L73.2",   "desc": "Hidradenitis suppurativa"},
        {"code": "L89.90",  "desc": "Pressure ulcer of unspecified site, unspecified stage"},
        # ── EYE (H00–H59) ────────────────────────────────────────────────────
        {"code": "H00.01",  "desc": "Hordeolum externum"},
        {"code": "H10.30",  "desc": "Unspecified acute conjunctivitis"},
        {"code": "H10.9",   "desc": "Unspecified conjunctivitis"},
        {"code": "H16.009", "desc": "Unspecified corneal ulcer, unspecified eye"},
        {"code": "H20.00",  "desc": "Acute and subacute iridocyclitis, unspecified"},
        {"code": "H33.009", "desc": "Unspecified retinal detachment with retinal break, unspecified eye"},
        {"code": "H34.10",  "desc": "Central retinal artery occlusion, unspecified eye"},
        {"code": "H40.211", "desc": "Acute angle-closure glaucoma, right eye"},
        {"code": "H47.01",  "desc": "Ischaemic optic neuropathy"},
        {"code": "H57.10",  "desc": "Ocular pain, unspecified eye"},
        # ── EAR (H60–H95) ────────────────────────────────────────────────────
        {"code": "H60.339", "desc": "Swimmer's ear, unspecified ear"},
        {"code": "H60.9",   "desc": "Unspecified otitis externa"},
        {"code": "H65.00",  "desc": "Acute serous otitis media, unspecified ear"},
        {"code": "H65.90",  "desc": "Unspecified nonsuppurative otitis media"},
        {"code": "H66.001", "desc": "Acute suppurative otitis media without spontaneous rupture of ear drum, right ear"},
        {"code": "H66.9",   "desc": "Otitis media, unspecified"},
        {"code": "H70.001", "desc": "Acute mastoiditis without complications, right ear"},
        {"code": "H81.09",  "desc": "Meniere's disease, unspecified ear"},
        {"code": "H81.391", "desc": "Other peripheral vertigo, right ear"},
        {"code": "H90.3",   "desc": "Sensorineural hearing loss, bilateral"},
        {"code": "H92.01",  "desc": "Otalgia, right ear"},
        {"code": "H93.11",  "desc": "Tinnitus, right ear"},
        # ── HAEMATOLOGY (D50–D89) ────────────────────────────────────────────
        {"code": "D50.0",   "desc": "Iron deficiency anaemia secondary to blood loss (chronic)"},
        {"code": "D50.9",   "desc": "Iron deficiency anaemia, unspecified"},
        {"code": "D51.0",   "desc": "Vitamin B12 deficiency anaemia due to intrinsic factor deficiency"},
        {"code": "D57.00",  "desc": "Hb-SS disease with crisis, unspecified"},
        {"code": "D57.1",   "desc": "Sickle-cell disease without crisis"},
        {"code": "D62",     "desc": "Acute posthemorrhagic anaemia"},
        {"code": "D64.9",   "desc": "Anaemia, unspecified"},
        {"code": "D65",     "desc": "Disseminated intravascular coagulation"},
        {"code": "D68.0",   "desc": "Von Willebrand's disease"},
        {"code": "D69.3",   "desc": "Immune thrombocytopenic purpura"},
        {"code": "D69.6",   "desc": "Thrombocytopenia, unspecified"},
        {"code": "D70.9",   "desc": "Neutropenia, unspecified"},
        {"code": "D72.829", "desc": "Elevated white blood cell count, unspecified"},
        {"code": "D84.9",   "desc": "Immunodeficiency, unspecified"},
        # ── INJURY & TRAUMA (S00–T98) ────────────────────────────────────────
        {"code": "S06.0X1A","desc": "Concussion with loss of consciousness of 30 minutes or less, initial encounter"},
        {"code": "S06.0X9A","desc": "Concussion with loss of consciousness of unspecified duration, initial encounter"},
        {"code": "S09.90XA","desc": "Unspecified injury of head, initial encounter"},
        {"code": "S22.000A","desc": "Wedge compression fracture of unspecified thoracic vertebra, initial encounter"},
        {"code": "S32.000A","desc": "Wedge compression fracture of unspecified lumbar vertebra, initial encounter"},
        {"code": "S39.012A","desc": "Strain of muscle, fascia and tendon of lower back, initial encounter"},
        {"code": "S42.001A","desc": "Fracture of unspecified part of clavicle, right side, initial encounter"},
        {"code": "S42.201A","desc": "Unspecified fracture of upper end of right humerus, initial encounter"},
        {"code": "S52.501A","desc": "Fracture of lower end of radius, right, initial encounter"},
        {"code": "S61.409A","desc": "Unspecified open wound of unspecified finger without damage to nail, initial encounter"},
        {"code": "S62.000A","desc": "Fracture of navicular bone of right wrist, displaced, initial encounter"},
        {"code": "S72.001A","desc": "Fracture of unspecified part of neck of right femur, initial encounter"},
        {"code": "S72.141A","desc": "Displaced intertrochanteric fracture of right femur, initial encounter"},
        {"code": "S82.201A","desc": "Unspecified fracture of shaft of right tibia, initial encounter"},
        {"code": "S92.001A","desc": "Fracture of calcaneus, right foot, initial encounter"},
        {"code": "T07",     "desc": "Unspecified multiple injuries"},
        {"code": "T14.90",  "desc": "Injury, unspecified"},
        {"code": "T20.00XA","desc": "Burn of unspecified degree of head, face and neck, initial encounter"},
        {"code": "T31.0",   "desc": "Burns involving less than 10% of body surface"},
        {"code": "T36.0X1A","desc": "Poisoning by penicillins, accidental, initial encounter"},
        {"code": "T39.1X1A","desc": "Poisoning by 4-Aminophenol derivatives (paracetamol), accidental, initial encounter"},
        {"code": "T40.0X1A","desc": "Poisoning by opium, accidental, initial encounter"},
        {"code": "T40.1X1A","desc": "Poisoning by heroin, accidental, initial encounter"},
        {"code": "T40.2X1A","desc": "Poisoning by other opioids, accidental, initial encounter"},
        {"code": "T40.4X1A","desc": "Poisoning by other synthetic narcotics, accidental, initial encounter"},
        {"code": "T42.4X1A","desc": "Poisoning by benzodiazepines, accidental, initial encounter"},
        {"code": "T43.011A","desc": "Poisoning by tricyclic antidepressants, accidental, initial encounter"},
        {"code": "T45.511A","desc": "Poisoning by anticoagulants, accidental, initial encounter"},
        {"code": "T50.901A","desc": "Poisoning by unspecified drugs, accidental, initial encounter"},
        {"code": "T51.0X1A","desc": "Toxic effect of ethanol, accidental, initial encounter"},
        {"code": "T58.01XA","desc": "Toxic effect of carbon monoxide from motor vehicle exhaust, accidental, initial encounter"},
        {"code": "T78.00XA","desc": "Anaphylactic reaction due to unspecified food, initial encounter"},
        {"code": "T78.2XXA","desc": "Anaphylactic shock, unspecified, initial encounter"},
        {"code": "T78.40XA","desc": "Allergy, unspecified, initial encounter"},
        {"code": "T79.4XXA","desc": "Traumatic shock, initial encounter"},
        # ── PREGNANCY (O00–O9A) ──────────────────────────────────────────────
        {"code": "O03.9",   "desc": "Complete or unspecified spontaneous abortion without complication"},
        {"code": "O13.3",   "desc": "Gestational hypertension without significant proteinuria, third trimester"},
        {"code": "O14.03",  "desc": "Mild to moderate pre-eclampsia, third trimester"},
        {"code": "O14.10",  "desc": "Severe pre-eclampsia, unspecified trimester"},
        {"code": "O20.0",   "desc": "Threatened abortion"},
        {"code": "O21.0",   "desc": "Mild hyperemesis gravidarum"},
        {"code": "O21.1",   "desc": "Hyperemesis gravidarum with metabolic disturbance"},
        {"code": "O23.10",  "desc": "Infections of bladder in pregnancy, unspecified trimester"},
        {"code": "O42.00",  "desc": "Premature rupture of membranes, onset of labour within 24 hours of rupture"},
        {"code": "O60.00",  "desc": "Preterm labour without delivery, unspecified trimester"},
        # ── NEOPLASMS — common ED presentations (C00–D49) ───────────────────
        {"code": "C18.9",   "desc": "Malignant neoplasm of colon, unspecified"},
        {"code": "C34.10",  "desc": "Malignant neoplasm of upper lobe, bronchus or lung, unspecified side"},
        {"code": "C50.912", "desc": "Malignant neoplasm of unspecified site of left female breast"},
        {"code": "C61",     "desc": "Malignant neoplasm of prostate"},
        {"code": "C67.9",   "desc": "Malignant neoplasm of bladder, unspecified"},
        {"code": "C71.9",   "desc": "Malignant neoplasm of brain, unspecified"},
        {"code": "C79.51",  "desc": "Secondary malignant neoplasm of bone"},
        {"code": "C80.1",   "desc": "Malignant (primary) neoplasm, unspecified"},
        {"code": "C85.10",  "desc": "Unspecified B-cell lymphoma, unspecified site"},
        {"code": "C91.00",  "desc": "Acute lymphoblastic leukaemia not having achieved remission"},
        {"code": "C92.00",  "desc": "Acute myeloblastic leukaemia, not having achieved remission"},
        # ── MISC / Z CODES ───────────────────────────────────────────────────
        {"code": "Z03.89",  "desc": "Encounter for observation for other suspected diseases and conditions ruled out"},
        {"code": "Z04.1",   "desc": "Encounter for examination and observation following transport accident"},
        {"code": "Z23",     "desc": "Encounter for immunisation"},
        {"code": "Z51.11",  "desc": "Encounter for antineoplastic chemotherapy"},
        {"code": "Z79.01",  "desc": "Long-term use of anticoagulants"},
        {"code": "Z79.4",   "desc": "Long-term use of insulin"},
        {"code": "Z87.891", "desc": "Personal history of nicotine dependence"},
        {"code": "Z91.010", "desc": "Allergy to peanuts"},
        {"code": "Z91.013", "desc": "Allergy to seafood"},
        {"code": "Z99.11",  "desc": "Dependence on respirator"},
    ]
    out: List[Dict[str, Any]] = []
    for row in icd:
        out.append(
            {
                "doc_type": "icd",
                "doc_id": f"icd:{row['code']}",
                "title": f"ICD {row['code']}",
                "text": f"{row['code']} | {row['desc']}",
                "icd_code": row["code"],
                "icd_desc": row["desc"],
            }
        )
    return out


def main() -> int:
    t0 = time.perf_counter()
    log("START 01_build_fake_kb_lancedb.py")

    log(f"Python exe: {sys.executable}")
    log(f"CWD: {os.getcwd()}")
    log(f"HF_HOME={os.getenv('HF_HOME')}")
    log(f"HF cache={os.getenv('HUGGINGFACE_HUB_CACHE')}")

    db_dir = Path(os.environ.get("LANCEDB_DIR", "/workspaces/codespaces-blank/lancedb_store"))
    db_dir.mkdir(parents=True, exist_ok=True)
    table_name = "kb_docs"

    log(f"Using LanceDB dir: {db_dir}")
    log(f"Table: {table_name}")

    log(f"Loading embedder: sentence-transformers/all-MiniLM-L6-v2  (KB: ~600 ICD-10 codes + schema docs)")
    t_emb = time.perf_counter()
    embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", device="cpu")
    log(f"Embedder ready in {time.perf_counter() - t_emb:.2f}s")

    docs = build_fake_schema_docs() + build_fake_icd_docs()
    log(f"Docs to embed: {len(docs)}")

    texts = [d["text"] for d in docs]
    log("Embedding docs...")
    t_vec = time.perf_counter()
    vecs = embedder.encode(texts, batch_size=64, normalize_embeddings=True, show_progress_bar=False)
    log(f"Embedding done in {time.perf_counter() - t_vec:.2f}s")

    for i in range(len(docs)):
        docs[i]["vector"] = vecs[i].tolist()

    log("Writing to LanceDB (overwrite)...")
    db = lancedb.connect(str(db_dir))
    db.create_table(table_name, data=docs, mode="overwrite")

    log("Preview 5 rows:")
    table = db.open_table(table_name)
    preview = table.to_pandas().head(5)
    print(preview[["doc_type", "doc_id", "title"]].to_string(index=False), flush=True)

    log(f"DONE in {time.perf_counter() - t0:.2f}s")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception:
        log("ERROR")
        traceback.print_exc()
        raise